export type AppLocale = 'id' | 'en';

const pageContent = {
  id: {
    home: {
      stats: [
        { value: '35+', label: 'Tahun Pengalaman' },
        { value: '120K', label: 'Hektar Lahan' },
        { value: '2.5M', label: 'Ton CPO/Tahun' },
        { value: '40+', label: 'Negara Mitra' },
      ],
      coreBusiness: {
        tag: 'Bisnis Inti',
        titleLines: ['Terintegrasi', 'Dari Hulu ke Hilir'],
        more: 'Selengkapnya',
        items: [
          {
            title: 'Perkebunan',
            subtitle: 'Agrikultur Berkelanjutan',
            desc: 'Pengelolaan 120.000 hektar lahan sawit secara profesional dengan standar Good Agricultural Practices (GAP) dan sertifikasi RSPO.',
          },
          {
            title: 'Produksi CPO',
            subtitle: 'Pengolahan Berteknologi Modern',
            desc: 'Fasilitas pabrik pengolahan modern berkapasitas 2,5 juta ton per tahun untuk menghasilkan Crude Palm Oil dan Palm Kernel berkualitas premium.',
          },
          {
            title: 'Distribusi',
            subtitle: 'Jaringan Logistik Global',
            desc: 'Jaringan distribusi yang menjangkau 40+ negara dengan armada logistik modern dan sistem rantai pasok terintegrasi.',
          },
        ],
      },
      about: {
        tag: 'Tentang Kami',
        titleLines: ['Dedikasi untuk', 'Kualitas & Keberlanjutan', 'Sejak 1990'],
        desc: 'PT Berlian Palm Oil Nusantara merupakan pionir dalam industri kelapa sawit di Indonesia. Kami tidak hanya berfokus pada hasil produksi, tetapi juga pelestarian lingkungan dan pemberdayaan masyarakat.',
        floatingStat: 'Tahun memimpin industri perkebunan sawit Indonesia',
        checklist: [
          'Standar Internasional RSPO & ISPO',
          'Fasilitas Produksi Berteknologi Modern',
          'Komitmen Tanpa Deforestasi (NDPE Policy)',
          'Program CSR untuk 50+ Komunitas Lokal',
        ],
        cta: 'Pelajari Lebih Lanjut',
        imageAlt: 'Kantor pusat BPON',
      },
      products: {
        tag: 'Produk Kami',
        title: 'Produk Unggulan',
        more: 'Lihat Semua Produk',
        items: [
          {
            name: 'Crude Palm Oil (CPO)',
            desc: 'Minyak sawit mentah berkualitas tinggi untuk industri pangan dan non-pangan.',
          },
          {
            name: 'Palm Kernel Oil (PKO)',
            desc: 'Minyak inti sawit premium untuk industri kosmetik dan oleokimia.',
          },
          {
            name: 'Palm Olein',
            desc: 'Fraksi cair minyak sawit untuk minyak goreng konsumsi berkualitas tinggi.',
          },
          {
            name: 'Palm Stearin',
            desc: 'Fraksi padat minyak sawit untuk industri margarin dan shortening.',
          },
        ],
      },
      sustainability: {
        tag: 'Keberlanjutan',
        title: 'Masa Depan Hijau Bersama BPON',
        desc: 'Keberlanjutan bukan sekadar tujuan - ini adalah cara kami berbisnis setiap harinya.',
        cta: 'Laporan Keberlanjutan 2024',
        items: [
          {
            title: 'Zero Deforestasi',
            desc: 'Kebijakan NDPE ketat tanpa ekspansi ke hutan primer.',
          },
          {
            title: 'Pemberdayaan Komunitas',
            desc: 'Program CSR aktif untuk 50+ komunitas di sekitar lahan operasional.',
          },
          {
            title: 'Reduksi Emisi',
            desc: 'Target net-zero emisi karbon sebelum tahun 2040.',
          },
          {
            title: 'Sertifikasi Internasional',
            desc: 'Tersertifikasi RSPO, ISPO, dan ISO 14001 untuk semua operasional.',
          },
        ],
      },
      news: {
        tag: 'Berita Terkini',
        title: 'Update Terbaru',
        more: 'Semua Berita',
        readMore: 'Baca Selengkapnya',
        items: [
          {
            date: 'April 2025',
            category: 'Korporat',
            title: 'BPON Raih Penghargaan RSPO Excellence in Sustainable Palm Oil 2025',
            excerpt: 'Penghargaan ini menegaskan komitmen BPON dalam menjalankan praktik perkebunan sawit yang bertanggung jawab dan berkelanjutan.',
          },
          {
            date: 'Maret 2025',
            category: 'Operasional',
            title: 'Ekspansi Fasilitas Pengolahan CPO di Kalimantan Timur Resmi Beroperasi',
            excerpt: 'Pabrik pengolahan terbaru dengan kapasitas 500.000 ton per tahun mulai beroperasi, meningkatkan total kapasitas produksi BPON.',
          },
          {
            date: 'Februari 2025',
            category: 'Keberlanjutan',
            title: 'BPON Luncurkan Program Replanting Sawit Ramah Lingkungan',
            excerpt: 'Program peremajaan kebun seluas 15.000 hektar menggunakan bibit unggul rendah karbon untuk mendukung target net-zero 2040.',
          },
        ],
      },
    },
    about: {
      heroAlt: 'Kantor pusat BPON',
      visionTitle: 'Visi',
      visionDesc: 'Menjadi perusahaan agribisnis kelapa sawit terkemuka di Asia Tenggara yang berkelanjutan, inovatif, dan memberikan nilai tambah bagi seluruh pemangku kepentingan.',
      missionTitle: 'Misi',
      missionItems: [
        'Mengelola perkebunan kelapa sawit dengan praktik pertanian terbaik dan berkelanjutan.',
        'Menghasilkan produk CPO dan turunannya berkualitas premium untuk pasar global.',
        'Memberdayakan komunitas lokal dan menciptakan lapangan kerja yang berkualitas.',
        'Menjaga kelestarian lingkungan melalui kebijakan NDPE yang ketat.',
        'Memberikan return yang optimal bagi pemegang saham dengan tata kelola yang baik.',
      ],
      profile: {
        tag: 'Profil Singkat',
        titleLines: ['35 Tahun Membangun', 'Industri Sawit', 'Indonesia'],
        paragraphs: [
          'PT Berlian Palm Oil Nusantara (BPON) berdiri pada tahun 1990 dan telah berkembang menjadi salah satu perusahaan perkebunan kelapa sawit terbesar di Indonesia. Dengan total lahan 120.000 hektar yang tersebar di lima provinsi, kami mengelola operasi yang terintegrasi dari perkebunan hingga distribusi global.',
          'Beroperasi dengan lisensi dan sertifikasi internasional, BPON berkomitmen untuk membuktikan bahwa bisnis sawit yang menguntungkan dan praktik lingkungan yang bertanggung jawab dapat berjalan berdampingan.',
        ],
        stats: [
          { value: '120K ha', label: 'Total Lahan' },
          { value: '5 Provinsi', label: 'Area Operasional' },
          { value: '18.000+', label: 'Karyawan' },
          { value: 'A+', label: 'Rating ESG Fitch' },
        ],
        imageAlt: 'Perkebunan BPON',
      },
      timeline: {
        tag: 'Perjalanan Kami',
        title: 'Tonggak Sejarah',
        items: [
          { year: '1990', event: 'BPON didirikan dengan lahan pertama seluas 500 hektar di Sumatera Selatan.' },
          { year: '2000', event: 'Ekspansi ke Kalimantan Tengah, total lahan mencapai 30.000 hektar.' },
          { year: '2008', event: 'Meraih sertifikasi RSPO pertama di Indonesia untuk operasional sawit berkelanjutan.' },
          { year: '2015', event: 'Kapasitas produksi CPO melampaui 1 juta ton per tahun.' },
          { year: '2020', event: 'Peluncuran kebijakan NDPE (No Deforestation, No Peat, No Exploitation).' },
          { year: '2025', event: 'Total lahan mencapai 120.000 hektar, beroperasi di 5 provinsi Indonesia.' },
        ],
      },
      leadership: {
        tag: 'Manajemen',
        title: 'Tim Kepemimpinan',
        members: [
          { name: 'Ir. Bambang Hartono', role: 'Direktur Utama', tenure: 'Sejak 2015' },
          { name: 'Dr. Siti Rahayu', role: 'Direktur Operasional', tenure: 'Sejak 2018' },
          { name: 'Agus Setiawan, MBA', role: 'Direktur Keuangan', tenure: 'Sejak 2016' },
          { name: 'Ir. Dewi Marlina', role: 'Direktur Keberlanjutan', tenure: 'Sejak 2020' },
        ],
      },
      cta: {
        title: 'Bergabunglah Bersama Kami',
        desc: 'Kami selalu membuka peluang kemitraan dan kolaborasi yang saling menguntungkan.',
        button: 'Hubungi Kami',
      },
    },
    business: {
      heroAlt: 'Operasional BPON',
      financials: [
        { label: 'Total Pendapatan 2024', value: 'Rp 28,5 T' },
        { label: 'EBITDA Margin', value: '24,8%' },
        { label: 'Total Aset', value: 'Rp 65,2 T' },
        { label: 'Pertumbuhan YoY', value: '12,3%' },
      ],
      units: {
        tag: 'Unit Bisnis',
        title: 'Tiga Pilar Bisnis Utama',
        desc: 'Operasional kami yang terintegrasi dari hulu ke hilir memastikan kontrol kualitas dan efisiensi di setiap tahap.',
        capacityLabel: 'Kapasitas',
        outputLabel: 'Output',
        items: [
          {
            title: 'Divisi Perkebunan',
            areas: ['Sumatera Selatan', 'Kalimantan Tengah', 'Kalimantan Timur', 'Riau', 'Papua Barat'],
            area: '120.000 ha',
            output: '2,8 juta ton TBS/tahun',
            highlights: [
              'Sertifikasi RSPO & ISPO di seluruh unit kebun.',
              'Program peremajaan sawit rakyat (PSR) bermitra dengan 12.000 petani.',
              'Sistem irigasi modern berbasis IoT untuk optimasi produksi.',
              'Pembibitan bersertifikat dengan produktivitas 30-35 ton TBS/ha/tahun.',
            ],
            imgSrc: '/images/biz-plantation.jpg',
          },
          {
            title: 'Divisi Pengolahan',
            areas: ['8 Pabrik PKS', '2 Refinery', '1 Oleochemical Plant'],
            area: '2,5 juta ton/tahun',
            output: 'CPO, PKO, Olein, Stearin',
            highlights: [
              'Teknologi pengolahan modern dengan efisiensi ekstraksi OER 23-25%.',
              'Sistem IPAL (pengolahan limbah cair) berstandar internasional.',
              'Fasilitas laboratorium QC terakreditasi ISO/IEC 17025.',
              'Kapasitas refinery 1 juta ton per tahun untuk produk hilir.',
            ],
            imgSrc: '/images/biz-processing.jpg',
          },
          {
            title: 'Divisi Distribusi',
            areas: ['40+ negara tujuan ekspor', '15 terminal tangki'],
            area: '40+ Negara',
            output: 'Ekspor & Domestik',
            highlights: [
              'Jaringan distribusi terintegrasi dari lahan hingga pelabuhan.',
              'Armada tanker khusus CPO berkapasitas total 500.000 DWT.',
              'Fasilitas tangki penyimpanan 300.000 ton di 4 pelabuhan utama.',
              'Sistem manajemen rantai pasok (SCM) real-time berbasis digital.',
            ],
            imgSrc: '/images/biz-distribution.jpg',
          },
        ],
      },
      integration: {
        tag: 'Model Bisnis',
        title: 'Integrasi Vertikal',
        desc: 'Kontrol penuh atas rantai nilai memungkinkan kami menjamin kualitas, efisiensi biaya, dan ketertelusuran produk.',
        steps: [
          { step: '01', label: 'Perkebunan', desc: 'Benih -> TBS' },
          { step: '02', label: 'Pengolahan', desc: 'TBS -> CPO/PKO' },
          { step: '03', label: 'Refinery', desc: 'CPO -> Olein/Stearin' },
          { step: '04', label: 'Distribusi', desc: 'Pelabuhan -> Global' },
        ],
      },
      cta: {
        title: 'Tertarik Bermitra dengan BPON?',
        desc: 'Hubungi tim bisnis kami untuk eksplorasi peluang kerjasama di sektor agribisnis kelapa sawit.',
        button: 'Diskusikan Kerjasama',
      },
    },
    products: {
      heroAlt: 'Produk minyak sawit',
      intro: 'Semua produk BPON diproduksi dengan standar kualitas ketat, tersertifikasi internasional, dan dapat ditelusuri dari kebun hingga ke tangan pelanggan.',
      certifications: ['RSPO Mass Balance', 'ISPO', 'ISCC', 'Halal MUI', 'ISO 22000 FSSC', 'Kosher Certified'],
      catalog: {
        tag: 'Portofolio',
        title: 'Katalog Produk',
        specTitle: 'Spesifikasi Produk',
        applicationTitle: 'Aplikasi Industri',
        items: [
          {
            id: 'cpo',
            name: 'Crude Palm Oil (CPO)',
            tag: 'Produk Utama',
            desc: 'Minyak sawit mentah berkualitas tinggi yang dihasilkan dari proses ekstraksi buah sawit segar. CPO BPON memenuhi standar internasional untuk industri pangan dan non-pangan.',
            specs: [
              { label: 'FFA (Free Fatty Acid)', value: '<= 3,5%' },
              { label: 'Kadar Air', value: '<= 0,15%' },
              { label: 'Kotoran', value: '<= 0,05%' },
              { label: 'Iodine Value', value: '50-55 g I2/100g' },
              { label: 'Melting Point', value: '33-39 C' },
            ],
            applications: ['Industri Pangan & Minyak Goreng', 'Industri Biodiesel', 'Industri Oleokimia', 'Sabun & Deterjen'],
            imgSrc: '/images/prod-cpo.jpg',
          },
          {
            id: 'pko',
            name: 'Palm Kernel Oil (PKO)',
            tag: 'Produk Premium',
            desc: 'Minyak inti sawit yang diekstraksi dari inti biji buah sawit. PKO memiliki sifat fisika-kimia unik yang sangat diminati untuk industri kosmetik dan oleokimia khusus.',
            specs: [
              { label: 'FFA', value: '<= 1,0%' },
              { label: 'Kadar Air', value: '<= 0,1%' },
              { label: 'Iodine Value', value: '14-22 g I2/100g' },
              { label: 'Saponification Value', value: '230-254 mg KOH/g' },
              { label: 'Melting Point', value: '24-26 C' },
            ],
            applications: ['Industri Kosmetik & Perawatan', 'Produk Bayi & Susu Formula', 'Oleokimia Khusus', 'Industri Farmasi'],
            imgSrc: '/images/prod-pko.jpg',
          },
          {
            id: 'olein',
            name: 'Refined Palm Olein (RPO)',
            tag: 'Produk Hilir',
            desc: 'Fraksi cair dari minyak sawit yang diproses melalui tahapan refined, bleached, dan deodorized. Produk utama untuk segmen minyak goreng konsumsi retail dan industrial.',
            specs: [
              { label: 'FFA', value: '<= 0,1%' },
              { label: 'Iodine Value', value: '>= 56 g I2/100g' },
              { label: 'Cloud Point', value: '<= 10 C' },
              { label: 'Color (5 1/4 Lovibond)', value: '<= 3R' },
              { label: 'Peroxide Value', value: '<= 1 meq/kg' },
            ],
            applications: ['Minyak Goreng Retail & Curah', 'Industri Snack & Makanan', 'Margarin & Shortening', 'Industri Roti & Kue'],
            imgSrc: '/images/prod-olein.jpg',
          },
          {
            id: 'stearin',
            name: 'Refined Palm Stearin (RPS)',
            tag: 'Produk Hilir',
            desc: 'Fraksi padat dari proses fraksinasi minyak sawit. Digunakan luas dalam industri margarin, shortening, dan oleokimia untuk menghasilkan produk dengan titik lebur yang lebih tinggi.',
            specs: [
              { label: 'FFA', value: '<= 0,1%' },
              { label: 'Iodine Value', value: '<= 48 g I2/100g' },
              { label: 'Melting Point', value: '44-56 C' },
              { label: 'Color (5 1/4 Lovibond)', value: '<= 3R' },
              { label: 'Peroxide Value', value: '<= 1 meq/kg' },
            ],
            applications: ['Margarin & Shortening', 'Cokelat & Confectionery', 'Sabun Batang', 'Biodiesel Campuran'],
            imgSrc: '/images/prod-stearin.jpg',
          },
        ],
      },
      cta: {
        title: 'Butuh Penawaran Harga atau Spesifikasi?',
        desc: 'Tim sales kami siap memberikan quotation dan spesifikasi lengkap sesuai kebutuhan industri Anda.',
        button: 'Minta Penawaran',
      },
    },
    sustainability: {
      heroAlt: 'Keberlanjutan BPON',
      commitment: {
        tag: 'Komitmen Kami',
        quote: 'Keberlanjutan adalah fondasi bisnis kami, bukan sekadar kewajiban.',
        desc: 'BPON percaya bahwa pertumbuhan bisnis yang kuat dan praktik lingkungan yang bertanggung jawab dapat berjalan beriringan. Strategi keberlanjutan kami terintegrasi penuh dalam setiap keputusan bisnis.',
      },
      pillars: {
        tag: '6 Pilar',
        title: 'Strategi Keberlanjutan',
        progressLabel: 'Progress',
        items: [
          {
            title: 'Tanpa Deforestasi',
            target: '0 ha hutan dibuka 2024',
            desc: 'Kebijakan NDPE (No Deforestation, No Peat, No Exploitation) kami melarang ekspansi ke kawasan hutan primer, gambut, dan area konservasi tinggi (HCV/HCS).',
            progress: 100,
          },
          {
            title: 'Energi Terbarukan',
            target: '65% energi dari biomassa',
            desc: 'Fasilitas pengolahan kami menggunakan biogas dari POME (Palm Oil Mill Effluent) dan cangkang kelapa sawit sebagai sumber energi terbarukan.',
            progress: 65,
          },
          {
            title: 'Manajemen Air',
            target: 'Reduksi 40% air tawar',
            desc: 'Sistem daur ulang air POME dan pemantauan sungai real-time untuk memastikan operasional kami tidak berdampak negatif pada sumber daya air sekitar.',
            progress: 72,
          },
          {
            title: 'Pemberdayaan Komunitas',
            target: '50+ komunitas dampingan',
            desc: 'Program CSR mencakup pendidikan, kesehatan, infrastruktur, dan pengembangan ekonomi bagi masyarakat di sekitar area operasional BPON.',
            progress: 85,
          },
          {
            title: 'Emisi Karbon',
            target: 'Net-zero sebelum 2040',
            desc: 'Roadmap dekarbonisasi kami mencakup reduksi emisi Scope 1, 2, dan 3 melalui efisiensi energi, penangkapan metana, dan program reforestasi.',
            progress: 38,
          },
          {
            title: 'Sertifikasi & Transparansi',
            target: '100% unit bersertifikasi RSPO',
            desc: 'Seluruh unit kebun dan pabrik kami bersertifikasi RSPO dan ISPO. Kami mempublikasikan Laporan Keberlanjutan tahunan sesuai standar GRI.',
            progress: 100,
          },
        ],
      },
      sdgs: {
        tag: 'PBB',
        title: 'Aligned dengan SDGs PBB',
        desc: 'Program keberlanjutan kami berkontribusi langsung pada pencapaian 8 dari 17 Tujuan Pembangunan Berkelanjutan PBB.',
        items: [
          { no: '2', label: 'Zero Hunger' },
          { no: '6', label: 'Clean Water' },
          { no: '7', label: 'Clean Energy' },
          { no: '8', label: 'Decent Work' },
          { no: '12', label: 'Responsible Consumption' },
          { no: '13', label: 'Climate Action' },
          { no: '15', label: 'Life on Land' },
          { no: '17', label: 'Partnerships' },
        ],
      },
      reports: {
        tag: 'Transparansi',
        title: 'Laporan Keberlanjutan',
        button: 'Unduh',
        items: [
          { year: '2024', title: 'Sustainability Report 2024', size: '8.2 MB' },
          { year: '2023', title: 'Sustainability Report 2023', size: '7.8 MB' },
          { year: '2022', title: 'Sustainability Report 2022', size: '6.5 MB' },
        ],
      },
      cta: {
        title: 'Bersama Membangun Masa Depan Hijau',
        desc: 'Pelajari lebih lanjut tentang program ESG kami atau hubungi tim sustainability BPON.',
        button: 'Hubungi Tim ESG',
      },
    },
    news: {
      heroAlt: 'Berita BPON',
      featuredTag: 'Berita Utama',
      allNewsTag: 'Semua Berita',
      featured: {
        date: '28 April 2025',
        category: 'Korporat',
        title: 'BPON Raih Penghargaan RSPO Excellence in Sustainable Palm Oil 2025',
        excerpt: 'PT Berlian Palm Oil Nusantara kembali meraih penghargaan bergengsi dari Roundtable on Sustainable Palm Oil (RSPO) untuk kategori Excellence in Sustainable Palm Oil Production. Penghargaan ini diberikan atas komitmen BPON dalam menjalankan praktik perkebunan yang bertanggung jawab selama lebih dari satu dekade.',
        imgSrc: '/images/news-featured.jpg',
      },
      articles: [
        {
          date: '15 April 2025',
          category: 'Operasional',
          title: 'Ekspansi Fasilitas Pengolahan CPO di Kalimantan Timur Resmi Beroperasi',
          excerpt: 'Pabrik pengolahan terbaru dengan kapasitas 500.000 ton per tahun mulai beroperasi, meningkatkan total kapasitas produksi BPON menjadi 2,5 juta ton per tahun.',
          imgSrc: '/images/news-expansion.jpg',
        },
        {
          date: '20 Maret 2025',
          category: 'Keberlanjutan',
          title: 'BPON Luncurkan Program Replanting Sawit Ramah Lingkungan 15.000 Ha',
          excerpt: 'Program peremajaan kebun seluas 15.000 hektar menggunakan bibit unggul rendah karbon untuk mendukung target net-zero 2040 sesuai Paris Agreement.',
          imgSrc: '/images/news-sustainability.jpg',
        },
        {
          date: '5 Maret 2025',
          category: 'Finansial',
          title: 'BPON Catat Pertumbuhan Pendapatan 12,3% di Tahun 2024',
          excerpt: 'Perusahaan mencatat pendapatan Rp 28,5 triliun pada FY2024, ditopang oleh peningkatan volume produksi dan kenaikan harga CPO di pasar global.',
          imgSrc: '/images/news-finance.jpg',
        },
        {
          date: '18 Februari 2025',
          category: 'CSR',
          title: 'Program Beasiswa BPON 2025 Buka Pendaftaran untuk 500 Mahasiswa',
          excerpt: 'BPON membuka pendaftaran beasiswa penuh untuk mahasiswa berprestasi di jurusan pertanian, teknik kimia, dan manajemen lingkungan dari 10 universitas mitra.',
          imgSrc: '/images/news-scholarship.jpg',
        },
        {
          date: '30 Januari 2025',
          category: 'Korporat',
          title: 'BPON Tandatangani MoU Ekspor CPO dengan Konsorsium Eropa Senilai USD 500 Juta',
          excerpt: 'Perjanjian kerjasama multitahun ini membuktikan kepercayaan pasar global terhadap kualitas dan sertifikasi produk sawit berkelanjutan dari BPON.',
          imgSrc: '/images/news-mou.jpg',
        },
        {
          date: '12 Januari 2025',
          category: 'Inovasi',
          title: 'BPON Investasi Rp 500 Miliar untuk Digitalisasi Operasional Kebun',
          excerpt: 'Transformasi digital mencakup implementasi IoT sensor, drone monitoring, dan platform AI untuk optimasi yield perkebunan di semua unit kebun BPON.',
          imgSrc: '/images/news-digital.jpg',
        },
      ],
      categoryColors: {
        Korporat: 'bg-blue-100 text-blue-700',
        Operasional: 'bg-orange-100 text-orange-700',
        Keberlanjutan: 'bg-green-100 text-green-700',
        Finansial: 'bg-purple-100 text-purple-700',
        CSR: 'bg-pink-100 text-pink-700',
        Inovasi: 'bg-cyan-100 text-cyan-700',
      },
    },
    contact: {
      heroAlt: 'Hubungi BPON',
      infoTag: 'Info Kontak',
      infoTitleLines: ['Kami Siap', 'Membantu Anda'],
      infoDesc: 'Apakah Anda memiliki pertanyaan tentang produk, ingin bermitra, atau sekadar ingin tahu lebih banyak tentang BPON? Tim kami siap membantu.',
      offices: [
        {
          type: 'Kantor Pusat',
          address: 'Gedung BPON Tower Lt. 15\nJl. Jend. Sudirman Kav. 1\nJakarta Pusat 10220',
          phone: '+62 21 1234 5678',
          email: 'info@bpon.co.id',
          hours: 'Senin-Jumat: 08:00-17:00 WIB',
        },
        {
          type: 'Kantor Regional Sumatera',
          address: 'Jl. Sudirman No. 88\nPalembang 30113\nSumatera Selatan',
          phone: '+62 711 123 4567',
          email: 'sumatra@bpon.co.id',
          hours: 'Senin-Jumat: 08:00-17:00 WIB',
        },
        {
          type: 'Kantor Regional Kalimantan',
          address: 'Jl. Ahmad Yani Km. 5\nBalikpapan 76114\nKalimantan Timur',
          phone: '+62 542 123 456',
          email: 'kaltim@bpon.co.id',
          hours: 'Senin-Jumat: 08:00-17:00 WITA',
        },
      ],
      subjects: [
        'Pertanyaan Umum',
        'Penawaran Produk & Harga',
        'Kerjasama & Kemitraan',
        'Investor Relations',
        'Media & Press',
        'Keberlanjutan & ESG',
        'Karir & Rekrutmen',
        'Lainnya',
      ],
      successTitle: 'Pesan Terkirim!',
      successDesc: 'Terima kasih telah menghubungi kami. Tim BPON akan merespons pesan Anda dalam 1-2 hari kerja.',
      formTitle: 'Kirim Pesan',
      companyLabel: 'Perusahaan',
      companyPlaceholder: 'Nama perusahaan Anda',
      subjectPlaceholder: 'Pilih topik pesan...',
      messageLabel: 'Pesan',
      messagePlaceholder: 'Tuliskan pesan Anda di sini...',
      emailLabel: 'Email',
      loadingText: 'Mengirim...',
      submitText: 'Kirim Pesan',
      mapTitle: 'Gedung BPON Tower',
      mapAddress: 'Jl. Jend. Sudirman Kav. 1, Jakarta Pusat',
    },
  },
  en: {
    home: {
      stats: [
        { value: '35+', label: 'Years of Experience' },
        { value: '120K', label: 'Hectares of Land' },
        { value: '2.5M', label: 'Tons of CPO/Year' },
        { value: '40+', label: 'Partner Countries' },
      ],
      coreBusiness: {
        tag: 'Core Business',
        titleLines: ['Integrated', 'From Plantation to Market'],
        more: 'Read More',
        items: [
          {
            title: 'Plantations',
            subtitle: 'Sustainable Agriculture',
            desc: 'We manage 120,000 hectares of palm estates with strong governance, Good Agricultural Practices (GAP), and RSPO certification.',
          },
          {
            title: 'CPO Production',
            subtitle: 'Modern Processing Facilities',
            desc: 'Our modern mills process up to 2.5 million tons per year, producing premium crude palm oil and palm kernel products.',
          },
          {
            title: 'Distribution',
            subtitle: 'Global Logistics Network',
            desc: 'An integrated supply chain and modern logistics fleet connect BPON products to customers in more than 40 countries.',
          },
        ],
      },
      about: {
        tag: 'About Us',
        titleLines: ['Dedicated to', 'Quality & Sustainability', 'Since 1990'],
        desc: 'PT Berlian Palm Oil Nusantara is a long-standing player in Indonesia\'s palm oil sector, balancing production excellence with environmental stewardship and community empowerment.',
        floatingStat: 'Years leading Indonesia\'s palm oil plantation industry',
        checklist: [
          'International RSPO & ISPO standards',
          'Modern production facilities',
          'No Deforestation commitment (NDPE Policy)',
          'CSR programs for 50+ local communities',
        ],
        cta: 'Learn More',
        imageAlt: 'BPON headquarters',
      },
      products: {
        tag: 'Our Products',
        title: 'Featured Products',
        more: 'View All Products',
        items: [
          {
            name: 'Crude Palm Oil (CPO)',
            desc: 'High-quality crude palm oil for food and non-food industries.',
          },
          {
            name: 'Palm Kernel Oil (PKO)',
            desc: 'Premium palm kernel oil for cosmetics and oleochemical applications.',
          },
          {
            name: 'Palm Olein',
            desc: 'The liquid palm fraction used for high-grade cooking oil products.',
          },
          {
            name: 'Palm Stearin',
            desc: 'The solid palm fraction for margarine, shortening, and industrial uses.',
          },
        ],
      },
      sustainability: {
        tag: 'Sustainability',
        title: 'A Greener Future with BPON',
        desc: 'Sustainability is not an add-on - it is embedded in how we operate every day.',
        cta: '2024 Sustainability Report',
        items: [
          {
            title: 'Zero Deforestation',
            desc: 'A strict NDPE policy with no expansion into primary forests.',
          },
          {
            title: 'Community Empowerment',
            desc: 'Active CSR programs that support more than 50 surrounding communities.',
          },
          {
            title: 'Emission Reduction',
            desc: 'A net-zero carbon target before 2040.',
          },
          {
            title: 'Global Certifications',
            desc: 'RSPO, ISPO, and ISO 14001 certification across operations.',
          },
        ],
      },
      news: {
        tag: 'Latest News',
        title: 'Recent Updates',
        more: 'All News',
        readMore: 'Read More',
        items: [
          {
            date: 'April 2025',
            category: 'Corporate',
            title: 'BPON Wins the RSPO Excellence in Sustainable Palm Oil 2025 Award',
            excerpt: 'The award reinforces BPON\'s commitment to responsible and sustainable plantation practices.',
          },
          {
            date: 'March 2025',
            category: 'Operations',
            title: 'New CPO Processing Expansion in East Kalimantan Starts Commercial Operations',
            excerpt: 'The new 500,000 ton facility is now operating and has increased BPON\'s total processing capacity.',
          },
          {
            date: 'February 2025',
            category: 'Sustainability',
            title: 'BPON Launches an Environmentally Responsible Palm Replanting Program',
            excerpt: 'A 15,000 hectare replanting initiative using low-carbon seedlings supports BPON\'s net-zero 2040 roadmap.',
          },
        ],
      },
    },
    about: {
      heroAlt: 'BPON headquarters',
      visionTitle: 'Vision',
      visionDesc: 'To become a leading Southeast Asian palm agribusiness company that is sustainable, innovative, and valuable to every stakeholder.',
      missionTitle: 'Mission',
      missionItems: [
        'Manage palm plantations with best-practice and sustainable agricultural methods.',
        'Deliver premium CPO and derivative products for global markets.',
        'Empower local communities and create quality employment opportunities.',
        'Protect the environment through strict NDPE implementation.',
        'Deliver strong returns for shareholders through sound governance.',
      ],
      profile: {
        tag: 'Company Profile',
        titleLines: ['35 Years Building', 'Indonesia\'s Palm Oil', 'Industry'],
        paragraphs: [
          'PT Berlian Palm Oil Nusantara (BPON) was founded in 1990 and has grown into one of Indonesia\'s major palm plantation companies. With 120,000 hectares across five provinces, we manage an integrated business from plantations to global distribution.',
          'Backed by international licenses and certifications, BPON is committed to proving that profitable palm oil operations and responsible environmental practices can go hand in hand.',
        ],
        stats: [
          { value: '120K ha', label: 'Total Estate Area' },
          { value: '5 Provinces', label: 'Operating Regions' },
          { value: '18,000+', label: 'Employees' },
          { value: 'A+', label: 'Fitch ESG Rating' },
        ],
        imageAlt: 'BPON plantation',
      },
      timeline: {
        tag: 'Our Journey',
        title: 'Key Milestones',
        items: [
          { year: '1990', event: 'BPON was founded with its first 500-hectare estate in South Sumatra.' },
          { year: '2000', event: 'Expansion into Central Kalimantan brought total managed area to 30,000 hectares.' },
          { year: '2008', event: 'BPON earned one of Indonesia\'s earliest RSPO certifications for sustainable palm operations.' },
          { year: '2015', event: 'CPO production capacity surpassed 1 million tons per year.' },
          { year: '2020', event: 'The company launched its NDPE policy: No Deforestation, No Peat, No Exploitation.' },
          { year: '2025', event: 'Total estate area reached 120,000 hectares across five Indonesian provinces.' },
        ],
      },
      leadership: {
        tag: 'Leadership',
        title: 'Executive Team',
        members: [
          { name: 'Bambang Hartono', role: 'President Director', tenure: 'Since 2015' },
          { name: 'Dr. Siti Rahayu', role: 'Operations Director', tenure: 'Since 2018' },
          { name: 'Agus Setiawan, MBA', role: 'Finance Director', tenure: 'Since 2016' },
          { name: 'Dewi Marlina', role: 'Sustainability Director', tenure: 'Since 2020' },
        ],
      },
      cta: {
        title: 'Build the Future with BPON',
        desc: 'We welcome partnership and collaboration opportunities that create long-term mutual value.',
        button: 'Contact Us',
      },
    },
    business: {
      heroAlt: 'BPON operations',
      financials: [
        { label: '2024 Revenue', value: 'IDR 28.5T' },
        { label: 'EBITDA Margin', value: '24.8%' },
        { label: 'Total Assets', value: 'IDR 65.2T' },
        { label: 'YoY Growth', value: '12.3%' },
      ],
      units: {
        tag: 'Business Units',
        title: 'Three Core Business Pillars',
        desc: 'Our vertically integrated operations give BPON strong control over quality, efficiency, and traceability at every stage.',
        capacityLabel: 'Capacity',
        outputLabel: 'Output',
        items: [
          {
            title: 'Plantation Division',
            areas: ['South Sumatra', 'Central Kalimantan', 'East Kalimantan', 'Riau', 'West Papua'],
            area: '120,000 ha',
            output: '2.8 million tons FFB/year',
            highlights: [
              'RSPO and ISPO certification across every estate unit.',
              'Smallholder replanting partnerships with 12,000 farmers.',
              'IoT-based irrigation systems to optimize field productivity.',
              'Certified nurseries with yields of 30-35 tons FFB/ha/year.',
            ],
            imgSrc: '/images/biz-plantation.jpg',
          },
          {
            title: 'Processing Division',
            areas: ['8 Palm Oil Mills', '2 Refineries', '1 Oleochemical Plant'],
            area: '2.5 million tons/year',
            output: 'CPO, PKO, Olein, Stearin',
            highlights: [
              'Modern processing technology with 23-25% OER extraction efficiency.',
              'International-standard wastewater treatment systems.',
              'Quality control laboratories accredited to ISO/IEC 17025.',
              'One million tons/year downstream refinery capacity.',
            ],
            imgSrc: '/images/biz-processing.jpg',
          },
          {
            title: 'Distribution Division',
            areas: ['40+ export destinations', '15 storage terminals'],
            area: '40+ Countries',
            output: 'Export & Domestic',
            highlights: [
              'Integrated distribution from estates to export ports.',
              'Dedicated CPO tanker fleet with 500,000 DWT total capacity.',
              '300,000 ton storage capacity across four key ports.',
              'Real-time digital supply chain management systems.',
            ],
            imgSrc: '/images/biz-distribution.jpg',
          },
        ],
      },
      integration: {
        tag: 'Business Model',
        title: 'Vertical Integration',
        desc: 'End-to-end control over the value chain allows BPON to protect quality, manage costs, and maintain traceability.',
        steps: [
          { step: '01', label: 'Plantation', desc: 'Seed -> FFB' },
          { step: '02', label: 'Processing', desc: 'FFB -> CPO/PKO' },
          { step: '03', label: 'Refinery', desc: 'CPO -> Olein/Stearin' },
          { step: '04', label: 'Distribution', desc: 'Port -> Global' },
        ],
      },
      cta: {
        title: 'Interested in Partnering with BPON?',
        desc: 'Speak with our business team to explore opportunities across the palm agribusiness value chain.',
        button: 'Start the Conversation',
      },
    },
    products: {
      heroAlt: 'Palm oil products',
      intro: 'Every BPON product is produced under strict quality standards, internationally certified, and traceable from plantation to customer.',
      certifications: ['RSPO Mass Balance', 'ISPO', 'ISCC', 'Halal MUI', 'ISO 22000 FSSC', 'Kosher Certified'],
      catalog: {
        tag: 'Portfolio',
        title: 'Product Catalog',
        specTitle: 'Product Specifications',
        applicationTitle: 'Industry Applications',
        items: [
          {
            id: 'cpo',
            name: 'Crude Palm Oil (CPO)',
            tag: 'Flagship Product',
            desc: 'High-quality crude palm oil extracted from fresh fruit bunches. BPON CPO meets international standards for food and industrial applications.',
            specs: [
              { label: 'FFA (Free Fatty Acid)', value: '<= 3.5%' },
              { label: 'Moisture', value: '<= 0.15%' },
              { label: 'Impurities', value: '<= 0.05%' },
              { label: 'Iodine Value', value: '50-55 g I2/100g' },
              { label: 'Melting Point', value: '33-39 C' },
            ],
            applications: ['Food & Cooking Oil', 'Biodiesel', 'Oleochemical Industry', 'Soap & Detergent'],
            imgSrc: '/images/prod-cpo.jpg',
          },
          {
            id: 'pko',
            name: 'Palm Kernel Oil (PKO)',
            tag: 'Premium Product',
            desc: 'Palm kernel oil extracted from the kernel of the fruit. PKO offers unique physical and chemical properties favored by cosmetics and specialty oleochemical industries.',
            specs: [
              { label: 'FFA', value: '<= 1.0%' },
              { label: 'Moisture', value: '<= 0.1%' },
              { label: 'Iodine Value', value: '14-22 g I2/100g' },
              { label: 'Saponification Value', value: '230-254 mg KOH/g' },
              { label: 'Melting Point', value: '24-26 C' },
            ],
            applications: ['Cosmetics & Personal Care', 'Baby Products & Formula', 'Specialty Oleochemicals', 'Pharmaceuticals'],
            imgSrc: '/images/prod-pko.jpg',
          },
          {
            id: 'olein',
            name: 'Refined Palm Olein (RPO)',
            tag: 'Downstream Product',
            desc: 'The liquid fraction of palm oil produced through refining, bleaching, and deodorizing. It is a core product for retail and industrial cooking oil segments.',
            specs: [
              { label: 'FFA', value: '<= 0.1%' },
              { label: 'Iodine Value', value: '>= 56 g I2/100g' },
              { label: 'Cloud Point', value: '<= 10 C' },
              { label: 'Color (5 1/4 Lovibond)', value: '<= 3R' },
              { label: 'Peroxide Value', value: '<= 1 meq/kg' },
            ],
            applications: ['Retail & Bulk Cooking Oil', 'Snack & Food Processing', 'Margarine & Shortening', 'Bakery'],
            imgSrc: '/images/prod-olein.jpg',
          },
          {
            id: 'stearin',
            name: 'Refined Palm Stearin (RPS)',
            tag: 'Downstream Product',
            desc: 'The solid fraction from palm oil fractionation. It is widely used in margarine, shortening, and oleochemical production where a higher melting point is required.',
            specs: [
              { label: 'FFA', value: '<= 0.1%' },
              { label: 'Iodine Value', value: '<= 48 g I2/100g' },
              { label: 'Melting Point', value: '44-56 C' },
              { label: 'Color (5 1/4 Lovibond)', value: '<= 3R' },
              { label: 'Peroxide Value', value: '<= 1 meq/kg' },
            ],
            applications: ['Margarine & Shortening', 'Chocolate & Confectionery', 'Bar Soap', 'Biodiesel Blends'],
            imgSrc: '/images/prod-stearin.jpg',
          },
        ],
      },
      cta: {
        title: 'Need Pricing or Product Specifications?',
        desc: 'Our sales team can provide quotations and detailed specifications for your industry requirements.',
        button: 'Request a Quote',
      },
    },
    sustainability: {
      heroAlt: 'BPON sustainability',
      commitment: {
        tag: 'Our Commitment',
        quote: 'Sustainability is the foundation of our business, not just a compliance exercise.',
        desc: 'BPON believes strong business growth and responsible environmental practices must advance together. Our sustainability strategy is integrated into every major business decision.',
      },
      pillars: {
        tag: 'Six Pillars',
        title: 'Sustainability Strategy',
        progressLabel: 'Progress',
        items: [
          {
            title: 'Zero Deforestation',
            target: '0 ha forest cleared in 2024',
            desc: 'Our NDPE policy prohibits expansion into primary forests, peatlands, and high conservation value or high carbon stock areas.',
            progress: 100,
          },
          {
            title: 'Renewable Energy',
            target: '65% energy from biomass',
            desc: 'Our processing facilities use POME biogas and palm kernel shells as renewable energy sources.',
            progress: 65,
          },
          {
            title: 'Water Stewardship',
            target: '40% freshwater reduction',
            desc: 'Water recycling systems and real-time river monitoring help ensure our operations do not harm local water resources.',
            progress: 72,
          },
          {
            title: 'Community Empowerment',
            target: '50+ supported communities',
            desc: 'CSR programs focus on education, healthcare, infrastructure, and livelihood development in nearby communities.',
            progress: 85,
          },
          {
            title: 'Carbon Emissions',
            target: 'Net-zero before 2040',
            desc: 'Our decarbonization roadmap addresses Scope 1, 2, and 3 emissions through efficiency, methane capture, and reforestation.',
            progress: 38,
          },
          {
            title: 'Certification & Transparency',
            target: '100% RSPO-certified units',
            desc: 'All estate and mill units are certified under RSPO and ISPO, supported by annual sustainability reporting aligned with GRI standards.',
            progress: 100,
          },
        ],
      },
      sdgs: {
        tag: 'UN',
        title: 'Aligned with the UN SDGs',
        desc: 'Our sustainability programs contribute directly to eight of the 17 United Nations Sustainable Development Goals.',
        items: [
          { no: '2', label: 'Zero Hunger' },
          { no: '6', label: 'Clean Water' },
          { no: '7', label: 'Clean Energy' },
          { no: '8', label: 'Decent Work' },
          { no: '12', label: 'Responsible Consumption' },
          { no: '13', label: 'Climate Action' },
          { no: '15', label: 'Life on Land' },
          { no: '17', label: 'Partnerships' },
        ],
      },
      reports: {
        tag: 'Transparency',
        title: 'Sustainability Reports',
        button: 'Download',
        items: [
          { year: '2024', title: 'Sustainability Report 2024', size: '8.2 MB' },
          { year: '2023', title: 'Sustainability Report 2023', size: '7.8 MB' },
          { year: '2022', title: 'Sustainability Report 2022', size: '6.5 MB' },
        ],
      },
      cta: {
        title: 'Building a Greener Future Together',
        desc: 'Learn more about our ESG agenda or speak with the BPON sustainability team.',
        button: 'Contact the ESG Team',
      },
    },
    news: {
      heroAlt: 'BPON news',
      featuredTag: 'Featured Story',
      allNewsTag: 'All News',
      featured: {
        date: 'April 28, 2025',
        category: 'Corporate',
        title: 'BPON Receives the RSPO Excellence in Sustainable Palm Oil 2025 Award',
        excerpt: 'PT Berlian Palm Oil Nusantara has once again received a prestigious award from the Roundtable on Sustainable Palm Oil (RSPO) in recognition of its long-term commitment to responsible plantation practices.',
        imgSrc: '/images/news-featured.jpg',
      },
      articles: [
        {
          date: 'April 15, 2025',
          category: 'Operations',
          title: 'Expanded CPO Processing Facility in East Kalimantan Begins Operations',
          excerpt: 'The new 500,000 ton-per-year plant is now operational, increasing BPON\'s total processing capacity to 2.5 million tons annually.',
          imgSrc: '/images/news-expansion.jpg',
        },
        {
          date: 'March 20, 2025',
          category: 'Sustainability',
          title: 'BPON Launches a 15,000 Hectare Low-Impact Replanting Program',
          excerpt: 'The program uses lower-carbon seedlings to support BPON\'s net-zero 2040 target and longer-term estate resilience.',
          imgSrc: '/images/news-sustainability.jpg',
        },
        {
          date: 'March 5, 2025',
          category: 'Financial',
          title: 'BPON Records 12.3% Revenue Growth in FY2024',
          excerpt: 'The company reported IDR 28.5 trillion in FY2024 revenue, supported by higher production volume and stronger global CPO prices.',
          imgSrc: '/images/news-finance.jpg',
        },
        {
          date: 'February 18, 2025',
          category: 'CSR',
          title: 'BPON 2025 Scholarship Program Opens for 500 University Students',
          excerpt: 'BPON has opened applications for full scholarships for students in agriculture, chemical engineering, and environmental management.',
          imgSrc: '/images/news-scholarship.jpg',
        },
        {
          date: 'January 30, 2025',
          category: 'Corporate',
          title: 'BPON Signs a USD 500 Million CPO Export MoU with a European Consortium',
          excerpt: 'The multi-year agreement highlights global market confidence in BPON\'s product quality and sustainability credentials.',
          imgSrc: '/images/news-mou.jpg',
        },
        {
          date: 'January 12, 2025',
          category: 'Innovation',
          title: 'BPON Invests IDR 500 Billion in Digital Plantation Operations',
          excerpt: 'The digital transformation program includes IoT sensors, drone monitoring, and AI-enabled yield optimization across BPON estates.',
          imgSrc: '/images/news-digital.jpg',
        },
      ],
      categoryColors: {
        Corporate: 'bg-blue-100 text-blue-700',
        Operations: 'bg-orange-100 text-orange-700',
        Sustainability: 'bg-green-100 text-green-700',
        Financial: 'bg-purple-100 text-purple-700',
        CSR: 'bg-pink-100 text-pink-700',
        Innovation: 'bg-cyan-100 text-cyan-700',
      },
    },
    contact: {
      heroAlt: 'Contact BPON',
      infoTag: 'Contact Information',
      infoTitleLines: ['We Are Ready', 'To Help You'],
      infoDesc: 'Whether you have questions about our products, want to discuss a partnership, or simply need more information about BPON, our team is ready to assist.',
      offices: [
        {
          type: 'Head Office',
          address: 'BPON Tower, 15th Floor\nJl. Jend. Sudirman Kav. 1\nCentral Jakarta 10220',
          phone: '+62 21 1234 5678',
          email: 'info@bpon.co.id',
          hours: 'Monday-Friday: 08:00-17:00 WIB',
        },
        {
          type: 'Sumatra Regional Office',
          address: 'Jl. Sudirman No. 88\nPalembang 30113\nSouth Sumatra',
          phone: '+62 711 123 4567',
          email: 'sumatra@bpon.co.id',
          hours: 'Monday-Friday: 08:00-17:00 WIB',
        },
        {
          type: 'Kalimantan Regional Office',
          address: 'Jl. Ahmad Yani Km. 5\nBalikpapan 76114\nEast Kalimantan',
          phone: '+62 542 123 456',
          email: 'kaltim@bpon.co.id',
          hours: 'Monday-Friday: 08:00-17:00 WITA',
        },
      ],
      subjects: [
        'General Inquiry',
        'Product Pricing & Offer',
        'Partnership Opportunity',
        'Investor Relations',
        'Media & Press',
        'Sustainability & ESG',
        'Careers & Recruitment',
        'Other',
      ],
      successTitle: 'Message Sent!',
      successDesc: 'Thank you for reaching out. The BPON team will respond within 1-2 business days.',
      formTitle: 'Send a Message',
      companyLabel: 'Company',
      companyPlaceholder: 'Your company name',
      subjectPlaceholder: 'Select a topic...',
      messageLabel: 'Message',
      messagePlaceholder: 'Write your message here...',
      emailLabel: 'Email',
      loadingText: 'Sending...',
      submitText: 'Send Message',
      mapTitle: 'BPON Tower',
      mapAddress: 'Jl. Jend. Sudirman Kav. 1, Central Jakarta',
    },
  },
} as const;

export function getLocalizedPageContent(locale: string) {
  return pageContent[locale === 'en' ? 'en' : 'id'];
}
